# Brew install packages
brew "neovim"
brew "bat"
brew "cmatrix"
brew "lazygit"
brew "neofetch"
brew "starship"
brew "python"
brew "ripgrep"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "tidy-viewer"
brew "starship"
brew "tmux"
brew "duckdb"
brew "fzf"

# Install Mac apps

# Cask install
# cask "git-credential-manager"
cask "1password"
cask "1password-cli"
# cask "kitty"
cask "ghostty"
cask "nikitabobko/tap/aerospace"
# cask "arc"
cask "google-chrome"
cask "appcleaner"
# cask "notion"
cask "spotify"
cask "affinity-designer"
cask "affinity-photo"
# cask "adobe-creative-cloud"
# cask "epic-games"
cask "raycast"
cask "discord"
cask "logi-options+"
# cask "pronotes"
cask "messenger"

# Brew tap
tap "saulpw/vd/visidata"
